export type PaperAssesmentDataType = {
  topicComment: string;
  topic: string;
  contributionComment: string;
  contribution: string;
  academicQualityComment: string;
  academicQuality: string;
  verificationOfResultsComment: string;
  verificationOfResults: string;
  noveltyComment: string;
  novelty: string;
  literatureReviewAndBibliographyComment: string;
  literatureReviewAndBibliography: string;
  languageComment: string;
  language: string;
  styleAndFormatComment: string;
  styleAndFormat: string;
  summary: string;
  commentsForOrganizingCommittee: string;
  recommendation: string;
};
